producto_1=input()
(a,b,c)=producto_1.split( )
a=int(a)
b=int(b)
c=float(c)
producto_2=input()
(d,e,f)=producto_2.split( )
d=int(d)
e=int(e)
f=float(f)
valor=(b*c)+(e*f)
print(f"VALOR A PAGAR: R$ {valor:0.2f}")